name: tests

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  test:
    name: test ${{ matrix.platform }} (${{ matrix.python-version }})
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
          pip install -e .[autogen]

      - uses: actions/cache@v2
        id: cache
        with:
          path: src/ome_types/loci_tools.jar
          key: ${{ hashFiles('src/ome_types/_bioformats.py') }}

      - name: Test with tox
        run: tox
        env:
          PLATFORM: ${{ matrix.platform }}
